### ISSUE TITLE
Pass vectors by reference

### ISSUE THREAD

**Issue by drake7707** [martinkersner/non-maximum-suppression-cpp#1]
All the vectors are copied on the stack in each function call, use & to pass them by reference.

**Comment by martinkersner** [comment]
Hi @drake7707 ,

Thank you for suggestion. Now, I pass vectors by reference. You can take a look at last [commit](https://github.com/martinkersner/non-maximum-suppression-cpp/commit/17b020235841662582ffdd36bc99e0f477465e42).

Martin
