### ISSUE TITLE
License

### ISSUE THREAD

**Issue by j-k** [martinkersner/non-maximum-suppression-cpp#6]
Which license is that code?

**Comment by martinkersner** [comment]
Hello @j-k!

Thank you for your interest in this code. I haven't assigned any license to it yet. What license would be good for your use?

Cheers,
Martin

**Comment by tatewake** [comment]
Hi @martinkersner ; sorry to bump an old github issue, but since it seems you're open to it, would you be willing to add the MIT license for this repo?

**Comment by martinkersner** [comment]
Hello @tatewake! I added MIT license (https://github.com/martinkersner/non-maximum-suppression-cpp/blob/master/LICENSE). Hope it helps 🙌
